### ISSUE TITLE
Alpine refactoring (v1.0 milestone)

### ISSUE THREAD

**Issue by harshangrjn** [lanl-ansi/Alpine.jl#216]
This issue is to keep track of the planned major refactoring for Alpine.jl. To complete this refactor, the following things need to be taken care of. This can be tagged as milestone for **v1.0** of Alpine.jl

**Relaxations and Algorithms**
- [ ] Implement/migrate all univariate piecewise relaxations and LP relaxations within Alpine, based on this paper: https://doi.org/10.1007/s11081-021-09609-z 
- [ ] Clean-up of multilinear term (SOS-2 based) relaxations 
  - [ ]  Add linking constraints across higher-order multilinear terms based on this paper: http://www.optimization-online.org/DB_HTML/2022/07/8974.html
  - [ ] Make each of the continuous and piecewise relaxations independently invokable from other JuMP-based packages
- [ ]  Partition Refinement Schemes
  - [ ] Clean-up adaptive/non-uniform (two) points around the LB solutions with a degree of freedom to choose the size of the added partition 
  - [ ] Implement single point at the LB solution
  - [ ] Implement/clean-up of bisection of largest partition when active partition cannot be further refined
  - [ ]  Add unit tests for all the above

**Presolve methods**
- [ ] Parsing: Clean up and fix open issues on parsing to isolate non-linear terms, create auxiliary variables and perform book-keeping
- [ ] Implement convexity detection of constraints and objective function and pre-filter them from partitioning 
- [ ] Special structure detection for bound propagation based on this paper: https://link.springer.com/article/10.1007/s11590-019-01396-y
- [ ] Add unit tests for all the above

**Documentation**
- [ ] Document all relaxations and update all function API references

**Comment by harshangrjn** [comment]
@kaarthiksundar Some of these were based out on your suggestions. Feel free to add to this list.

**Comment by kaarthiksundar** [comment]
Relaxations and algorithms - all of it is now implemented in PolyhedralRelaxations including unit tests. So I think it is double work to do it again in an independently invokable manner. 

I will work on implementing the presolve methods as modules. After I am done with that I will work on pulling everything to Alpine.

**Comment by harshangrjn** [comment]
Firstly, we did not have such plans/discussions, whatsoever, to replicate and move relaxations and algorithms to separate packages. So I strongly think let's keep these two within Alpine. Alpine mainly needs univariate relaxations for transcendental functions, which we can always implement later depending on availability of time and resources. If you concur, we can go ahead with presolve modules and expression parsing module clean ups. Else, things can wait.

**Comment by kaarthiksundar** [comment]
I will give it some thought. I am mainly thinking on the software engineering aspects because the two main goals implementing all the relaxations in Alpine while at the same time wanting independent invokability of the relaxations are at odds with each other. The separate packages idea give independent invokability that you are asking for anyway and using them within Alpine will ensure easily maintainability in the long run because now, you have the exact same relaxations in two code bases. I can vouch for the independent invokability part because we have used these packages for other problems.

**Comment by harshangrjn** [comment]
As mentioned earlier very clearly, this invokability is quite straightforward to be done in Alpine too. All the modules of relaxations will stay separate, and Alpine's partitioning algorithm (with more options which is currently being implemented) will take care of interplay between relaxations, parsing and heuristics, as it is already done within it. Moreover, having relaxations and algorithms within Alpine will make this interplay much easier, even from a software perspective in my opinion. Say we replicate Juniper's branch and bound algorithm on a private repo (which is already a bit creepy) and then claim the algorithm has to be moved out of Juniper is a bit meaningless, isnt it? In summary, I frankly I think this discussion is a bit wasteful, but that said Alpine certainly needs a major overhaul which will be done incrementally and your feedback is welcome. We can discuss more if need be.
